test: cd workflow

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -16,39 +16,38 @@ concurrency:
   cancel-in-progress: false # Do not cancel any in-progress runs
 
 jobs:
-  deploy:
-    if: ${{ github.event.workflow_run.conclusion == 'success' }}
-    environment:
-      name: build
-      url: ${{ steps.deployment.outputs.page_url }}
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Get the run ID of the last successful CI workflow
-        id: get_run_id
-        run: |
-          CI_RUN_ID=$(gh run list --workflow "Continuous Integration" --json databaseId,status --limit 1 | jq -r '.[0].databaseId')
-          if [ -z "$CI_RUN_ID" ]; then
-            echo "Erro: Não foi possível encontrar o último run bem-sucedido do CI"
-            exit 1
-          fi
-          echo "ci_run_id=$CI_RUN_ID" >> $GITHUB_ENV
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Download artifact from CI
-        uses: actions/download-artifact@v4
-        with:
+    deploy:
+        if: ${{ github.event.workflow_run.conclusion == 'success' }}
+        environment:
           name: build
-          github-token: ${{ secrets.ARTIFACT_DEPLOY_TOKEN }}
-          run-id: ${{ env.ci_run_id }}
+          url: ${{ steps.deployment.outputs.page_url }}
+        runs-on: ubuntu-latest
+        steps:
+          - name: Checkout code
+            uses: actions/checkout@v4
+            with:
+              fetch-depth: 0
 
-      - name: Deploy to GitHub Pages
-        id: deployment
-        uses: actions/deploy-pages@v4
-        with:
-          artifact_name: build
+          - name: Get the run ID of the last successful CI workflow
+            id: get_run_id
+            run: |
+              CI_RUN_ID=$(gh run list --workflow "Continuous Integration" --json databaseId,status --limit 1 | jq -r '.[0].databaseId')
+              if [ -z "$CI_RUN_ID" ]; then
+                echo "Error: Could not find the last successful CI run."
+                exit 1
+              fi
+              echo "ci_run_id=$CI_RUN_ID" >> $GITHUB_ENV
+            env:
+              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+          - name: Download build artifact from CI
+            uses: actions/download-artifact@v4
+            with:
+              name: build
+              run-id: ${{ env.ci_run_id }}
+
+          - name: Deploy to GitHub Pages
+            id: deployment
+            uses: actions/deploy-pages@v4
+            with:
+              artifact_name: build
